# Generated by Django 3.2.4 on 2022-08-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_url_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='ip',
            field=models.GenericIPAddressField(default=0),
            preserve_default=False,
        ),
    ]
