# Generated by Django 3.2.4 on 2022-08-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_alter_url_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='ip',
            field=models.GenericIPAddressField(editable=False, verbose_name='Ip Address'),
        ),
        migrations.AlterField(
            model_name='url',
            name='uuid',
            field=models.CharField(max_length=10),
        ),
    ]
