# Generated by Django 3.2.4 on 2022-08-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0007_auto_20220801_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='uuid',
            field=models.CharField(max_length=20),
        ),
    ]
