# Generated by Django 3.2.4 on 2022-08-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0004_auto_20220801_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='ip',
            field=models.GenericIPAddressField(editable=False, verbose_name='Ip Address'),
        ),
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.CharField(editable=False, max_length=10000),
        ),
        migrations.AlterField(
            model_name='url',
            name='uuid',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
