# Generated by Django 3.2.4 on 2022-08-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0008_alter_url_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='uuid',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
